[package]
name = "gui"
version = "0.1.0"
authors = ["axelamit <axel.v.nilsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_engine = {path = "../chess_engine"}
ggez = "0.5"
dialog = "0.3.0"